#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Radio_BDModel;

namespace Radio_BDModel	
{
	public partial class Avaliacao
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _nota;
		public virtual string Nota
		{
			get
			{
				return this._nota;
			}
			set
			{
				this._nota = value;
			}
		}
		
		private string _comentario;
		public virtual string Comentario
		{
			get
			{
				return this._comentario;
			}
			set
			{
				this._comentario = value;
			}
		}
		
		private int? _id_programa;
		public virtual int? Id_programa
		{
			get
			{
				return this._id_programa;
			}
			set
			{
				this._id_programa = value;
			}
		}
		
		private Programa _programa;
		public virtual Programa Programa
		{
			get
			{
				return this._programa;
			}
			set
			{
				this._programa = value;
			}
		}
		
	}
}
#pragma warning restore 1591
