#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Radio_BDModel;

namespace Radio_BDModel	
{
	public partial class Cadastro_usuario
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _nome;
		public virtual string Nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		
		private string _cpf;
		public virtual string Cpf
		{
			get
			{
				return this._cpf;
			}
			set
			{
				this._cpf = value;
			}
		}
		
		private string _senha;
		public virtual string Senha
		{
			get
			{
				return this._senha;
			}
			set
			{
				this._senha = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private IList<Pedido_musica> _pedido_musicas = new List<Pedido_musica>();
		public virtual IList<Pedido_musica> Pedido_musicas
		{
			get
			{
				return this._pedido_musicas;
			}
		}
		
	}
}
#pragma warning restore 1591
