#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Radio_BDModel;

namespace Radio_BDModel	
{
	public partial class RadioModel : OpenAccessContext, IRadioModelUnitOfWork
	{
		private static string connectionStringName = @"RadiocorredorConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public RadioModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public RadioModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public RadioModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public RadioModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public RadioModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Programa> Programas 
		{
			get
			{
				return this.GetAll<Programa>();
			}
		}
		
		public IQueryable<Pedido_musica> Pedido_musicas 
		{
			get
			{
				return this.GetAll<Pedido_musica>();
			}
		}
		
		public IQueryable<Cadastro_usuario> Cadastro_usuarios 
		{
			get
			{
				return this.GetAll<Cadastro_usuario>();
			}
		}
		
		public IQueryable<Avaliacao> Avaliacaos 
		{
			get
			{
				return this.GetAll<Avaliacao>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of RadioModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of RadioModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IRadioModelUnitOfWork : IUnitOfWork
	{
		IQueryable<Programa> Programas
		{
			get;
		}
		IQueryable<Pedido_musica> Pedido_musicas
		{
			get;
		}
		IQueryable<Cadastro_usuario> Cadastro_usuarios
		{
			get;
		}
		IQueryable<Avaliacao> Avaliacaos
		{
			get;
		}
	}
}
#pragma warning restore 1591
