#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Radio_BDModel;

namespace Radio_BDModel	
{
	public partial class Pedido_musica
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _nome_musica;
		public virtual string Nome_musica
		{
			get
			{
				return this._nome_musica;
			}
			set
			{
				this._nome_musica = value;
			}
		}
		
		private DateTime? _data;
		public virtual DateTime? Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		
		private int? _id_ouvinte;
		public virtual int? Id_ouvinte
		{
			get
			{
				return this._id_ouvinte;
			}
			set
			{
				this._id_ouvinte = value;
			}
		}
		
		private Cadastro_usuario _cadastro_usuario;
		public virtual Cadastro_usuario Cadastro_usuario
		{
			get
			{
				return this._cadastro_usuario;
			}
			set
			{
				this._cadastro_usuario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
